doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: 'mariadb-10.5.8'
        charset: UTF8
        url: "mysql://ephec:Ephec123@bb803920-001.dbaas.ovh.net:35762/mysql1"

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
